# Generated by Django 3.2.25 on 2025-11-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250802_2339'),
        ('products', '0003_auto_20251105_1310'),
    ]

    operations = [
    ]
